const paraTag = document.querySelector("p");

document
  .querySelector("button")
  .addEventListener("click", randomQuoteGenerator);

const motivationalQuotes = [
  "Code is like humor. When you have to explain it, it’s bad.",
  "The best error message is the one that never shows up.",
  "Code without tests is like a ship without a captain.",
  "Your time is limited, don't waste it living someone else's life. Code your own path.",
  "The best way to predict your future is to create it.",
  "Coding is not just code, that is a live thing to serve your life.",
  "The only way to do great work is to love what you do.",
  "Success is stumbling from failure to failure with no loss of enthusiasm.",
  "Don't watch the clock; do what it does. Keep going.",
  "The only place where success comes before work is in the dictionary.",
  "It’s not a bug. It’s an undocumented feature.",
  "Code, ship, repeat.",
  "Programmers don't die, they just go offline.",
  "Every artist was first an amateur.",
  "Code as if the next person to maintain your code is a maniac serial killer who knows where you live.",
  "The function of good software is to make the complex appear simple.",
  "To iterate is human, to recurse divine.",
  "There are only two hard things in computer science: cache invalidation and naming things.",
  "Make it work, make it right, make it fast.",
  "Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday’s code.",
  "Don’t be afraid to break things. It's a necessary part of the learning process.",
  "Perfection is achieved not when there is nothing more to add, but rather when there is nothing more to take away.",
  "The best way to predict the future is to implement it.",
  "Debugging is like being the detective in a crime movie where you are also the murderer.",
  "Programming isn’t about what you know; it’s about what you can figure out.",
  "The joy of coding Python should be in seeing short, concise, readable classes that express a lot of action in a small amount of clear code.",
  "Talk is cheap. Show me the code.",
  "Don't be a programmer, be a problem solver.",
  "If you think math is hard, try web design.",
  "In the world of coding, patience is the most important virtue.",
  "The only code that is always bug-free is the one you never write.",
  "Code is like humor. When you have to explain it, it’s bad.",
  "The best way to predict the future is to implement it.",
  "If you want to set off and go develop some grand new thing, you don’t need millions of dollars of capitalization. You need enough pizza and Diet Coke to stick in your refrigerator, a cheap PC to work on, and the dedication to go through with it.",
  "Perfection is achieved not when there is nothing more to add, but rather when there is nothing more to take away.",
  "The computer was born to solve problems that did not exist before.",
  "There are 10 types of people in the world: Those who understand binary, and those who don’t.",
  "It’s not a bug. It’s an undocumented feature.",
  "When to use iterative development? You should use iterative development only on projects that you want to succeed.",
  "It’s harder to read code than to write it.",
  "Software and cathedrals are much the same – first we build them, then we pray.",
  "Sometimes it is the people no one can imagine anything of who do the things no one can imagine.",
  "Code is read much more often than it is written.",
  "Learning to code is useful no matter what your career ambitions are.",
  "It's not about how much you know, it's about how much you can figure out.",
  "Coding is not just code, that is a live thing to serve your life.",
  "You don't have to be a genius to code, just be yourself.",
  "The more you code, the less mysterious coding becomes.",
  "Coding is the language of the future, and every girl should learn it.",
  "Writing code is like writing poetry.",
  "You don't have to be great to start, but you have to start to be great.",
  "Don't compare yourself to others; compare yourself to the person you were yesterday.",
  "Coding is not a job; it's a language of expression.",
  "The secret to coding is having fun while learning.",
  "The best way to learn is by doing.",
  "Every problem can be solved with a cup of coffee and some lines of code.",
  "The beauty of coding is in its infinite possibilities.",
  "Embrace the bugs; they are the stepping stones to success.",
  "The best error message is the one that never shows up.",
  "Debugging is the art of fixing bugs without introducing new ones.",
  "You are never too old to start coding.",
  "A programmer's life is all about coffee, code, and conquer.",
  "The best coders are the laziest ones; they automate everything.",
  "Keep coding and stay curious; the world is your playground.",
  "The best way to predict your future is to create it.",
  "Programming is not just a skill; it's a mindset.",
  "Don't just code; create something amazing.",
  "Coding is not a destination; it's a journey of continuous learning.",
  "Challenges are opportunities in disguise; embrace them.",
  "Your attitude determines your direction in coding and in life.",
  "Every line of code is a step towards a better future.",
  "The more you code, the more you discover the beauty of simplicity.",
  "Code is the canvas, and the developer is the artist.",
  "Don't fear bugs; they are your companions on the road to mastery.",
  "Coding is not a sprint; it's a marathon of creative problem-solving.",
  "A coder's mindset: I don't break code; I improve it.",
  "Be patient; coding mastery is a journey, not a destination.",
  "Code is the poetry of a logical mind.",
  "Your code is a reflection of your thought process.",
  "The best code is not the one you write; it's the one you refactor.",
  "Programming is not about typing; it's about thinking.",
  "Every project is a lesson; learn from both success and failure.",
  "Coding is not just a job; it's a way of thinking.",
  "The best error message is the one that guides you to the solution.",
  "Code like you'll live forever, live like you'll code today.",
  "The beauty of coding is turning ideas into reality.",
  "Code is a conversation between humans and computers.",
  "Programming is an art, and every coder is an artist.",
  "Code is not a set of instructions; it's a form of self-expression.",
  "The best programs are written when the programmer is in a flow state.",
  "Code is not just a tool; it's a means of creating something extraordinary.",
  "Your code is a legacy; write it with pride.",
  "A coder's journey: from 'Hello World' to 'Hello Universe'.",
  "Coding is the bridge between imagination and reality.",
  "Programmers don't die; they just go offline.",
  "Coding is not a race; it's a dance with logic.",
  " Debugging is like solving a mystery; enjoy the adventure.",
  "Code like nobody is watching, but debug like everyone is.",
  "The best way to predict your coding future is to start coding.",
  " Coding is not just about creating software; it's about solving real-world problems.",
];

function randomQuoteGenerator() {
  let randomNumber = Math.floor(Math.random() * 100);
  paraTag.textContent = motivationalQuotes[randomNumber];
}
